/**
 * AI Agent Fix Prompt Generator
 *
 * Generates structured prompts for AI coding assistants (Claude Code, GitHub Copilot, Cursor, etc.)
 * to help fix issues identified by RCA analysis.
 */

/**
 * Context for generating a fix prompt
 */
export interface FixPromptContext {
  // Alert context
  alertName: string;
  alertType: string;
  currentValue: number;
  threshold: number;
  triggeredAt: string;

  // RCA analysis
  hypothesis: string;
  confidence: number;
  category: string;
  reasoning: string;
  evidence: string[];

  // Code context
  suspectedFiles: Array<{
    path: string;
    startLine: number;
    endLine: number;
    content: string;
    similarity: number;
  }>;

  // Related changes
  relatedCommits: Array<{
    sha: string;
    message: string;
    author: string;
    relevance: string;
  }>;

  // Remediation
  immediateSteps: string[];
  longTermSteps: string[];

  // Repository info
  repoUrl?: string;
  defaultBranch?: string;
}

/**
 * Category labels for display in prompts
 */
const CATEGORY_LABELS: Record<string, string> = {
  CODE_CHANGE: "Code Change",
  INFRASTRUCTURE: "Infrastructure",
  EXTERNAL_DEPENDENCY: "External Dependency",
  DATA_ISSUE: "Data Issue",
  CONFIGURATION: "Configuration",
  UNKNOWN: "Unknown",
};

/**
 * Alert type labels for display
 */
const ALERT_TYPE_LABELS: Record<string, string> = {
  ERROR_RATE: "Error Rate",
  LATENCY_P50: "P50 Latency",
  LATENCY_P95: "P95 Latency",
  LATENCY_P99: "P99 Latency",
};

/**
 * Generate a structured fix prompt for AI coding assistants
 */
export function generateFixPrompt(context: FixPromptContext): string {
  const {
    alertName,
    alertType,
    currentValue,
    threshold,
    triggeredAt,
    hypothesis,
    confidence,
    category,
    reasoning,
    evidence,
    suspectedFiles,
    relatedCommits,
    immediateSteps,
    longTermSteps,
    repoUrl,
  } = context;

  const confidencePercent = Math.round(confidence * 100);
  const categoryLabel = CATEGORY_LABELS[category] ?? category;
  const alertTypeLabel = ALERT_TYPE_LABELS[alertType] ?? alertType;

  let prompt = `# Fix Request: ${alertName}

## Problem Summary

**Alert Type:** ${alertTypeLabel}
**Triggered:** ${triggeredAt}
**Current Value:** ${formatValue(alertType, currentValue)} (Threshold: ${formatValue(alertType, threshold)})

## Root Cause Analysis (${confidencePercent}% confidence)

**Hypothesis:** ${hypothesis}

**Category:** ${categoryLabel}

**Reasoning:** ${reasoning}

**Evidence:**
${evidence.map((e) => `- ${e}`).join("\n")}

`;

  // Add suspected files
  if (suspectedFiles.length > 0) {
    prompt += `## Suspected Code Locations

The following files have been identified as potentially related to the issue:

`;
    for (const file of suspectedFiles.slice(0, 5)) {
      const similarityPercent = Math.round(file.similarity * 100);
      prompt += `### ${file.path}:${file.startLine}-${file.endLine} (${similarityPercent}% match)

\`\`\`
${file.content}
\`\`\`

`;
    }
  }

  // Add related commits
  if (relatedCommits.length > 0) {
    prompt += `## Related Recent Changes

These recent commits may be related to the issue:

`;
    for (const commit of relatedCommits.slice(0, 3)) {
      prompt += `- **${commit.sha.slice(0, 7)}** (${commit.relevance} relevance): ${commit.message} - by ${commit.author}
`;
    }
    prompt += "\n";
  }

  // Add remediation steps
  prompt += `## Suggested Fix Approach

### Immediate Steps:
${immediateSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

### Long-term Improvements:
${longTermSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

## Instructions

Please analyze the code locations above and implement a fix that:
1. Addresses the root cause identified in the hypothesis
2. Follows the immediate remediation steps
3. Includes appropriate error handling
4. Adds tests to prevent regression

`;

  if (repoUrl) {
    prompt += `**Repository:** ${repoUrl}
`;
  }

  prompt += `
---
*This fix prompt was generated by CognObserve RCA System*
`;

  return prompt;
}

/**
 * Format value based on alert type
 */
function formatValue(alertType: string, value: number): string {
  if (alertType === "ERROR_RATE") {
    return `${value.toFixed(2)}%`;
  }
  return `${value.toFixed(0)}ms`;
}
